# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-04 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190214_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='personal_pronoun',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='gender',
            field=models.CharField(choices=[('M', 'Man'), ('F', 'Woman')], max_length=1),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_size',
            field=models.CharField(blank=True, choices=[('XS', 'XS - Extra Small'), ('S', 'S - Small'), ('M', 'M - Medium'), ('L', 'L - Large'), ('XL', 'XL -Extra Large'), ('XXL', 'XXL - Extra Extra Large')], max_length=45),
        ),
        migrations.AlterField(
            model_name='playerratings',
            name='athleticism',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'I am slow, it is hard to change direction, and am easily winded.'), (2, 'I can change direction decently, but need to rest often.'), (3, 'I am somewhat fast, can make hard cuts, and can play for a few minutes at a time before resting.'), (4, 'I am fairly fast, can change direction and react well, and can play a few hard points in a row.'), (5, 'I am very fast, can turn well, jump high, and need little rest.'), (6, 'I am faster than anyone on the field at any level and enjoy playing almost every point.')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playerratings',
            name='competitiveness',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'I do not care whether I win or lose, I play purely to socialize and have fun.'), (2, 'I play ultimate to have fun, but would prefer to win.'), (3, 'I am competitive, fight to win close games, and am somewhat disappointed by a loss.'), (4, 'I am extremely competitive and am very disappointed by a loss.')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playerratings',
            name='experience',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'I am new to ultimate or have played less than 2 years of pickup.'), (2, 'I have played in an organized league or on a high school team for 1-2 seasons, or pickup for 3+ years.'), (3, 'I have played in an organized league or on a high school team for 3+ seasons.'), (4, 'I have played on a college or club team in the last 6 years.'), (5, 'I have played multiple seasons on a college or club team in the last 4 years.'), (6, 'I have played multiple seasons on a regionals or nationals-level college or club team in the last 4 years.')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playerratings',
            name='ratings_type',
            field=models.PositiveIntegerField(choices=[(1, 'Captain'), (2, 'Junta'), (3, 'User')]),
        ),
        migrations.AlterField(
            model_name='playerratings',
            name='strategy',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'I am new to organized ultimate.'), (2, 'I have basic knowledge of the game (e.g. stall counts, pivoting).'), (3, 'I have moderate knowledge (e.g. vertical stack, force, basic man defense).'), (4, 'I have advanced knowledge (e.g. zone defense, horizontal stack, switching).'), (5, 'I am familiar enough with the above concepts that I could explain them to a new player.'), (6, 'I would consider myself an expert in ultimate strategy.')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playerratings',
            name='throwing',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 'I am a novice or am learning to throw.'), (2, 'I can throw a backhand 10 yards with 90% confidence.'), (3, 'I can throw a forehand 10+ yards with 90% confidence and can handle if needed.'), (4, 'I am confident throwing forehand and backhand various distances and can handle at a league level.'), (5, 'I am confident throwing break throws and can be a very good league-level handler.'), (6, 'I am confident in many styles of throws and could be a college or club-level handler.')], default=None, null=True),
        ),
    ]
