# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-04 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20200204_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerConcussionWaiver',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='concussion_waivers/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], max_length=32)),
                ('submitted_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_concussion_waiver_reviewed_by_set', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_concussion_waiver_submitted_by_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
