# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-09 18:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_playerconcussionwaiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerconcussionwaiver',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_concussion_waiver_reviewed_by_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='playerconcussionwaiver',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], max_length=32),
        ),
        migrations.AlterField(
            model_name='playerconcussionwaiver',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_concussion_waiver_submitted_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
