# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-09 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200209_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerconcussionwaiver',
            name='status',
            field=models.CharField(choices=[('not_submitted', 'Not Submitted'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('denied', 'Denied')], default='not_submitted', max_length=32),
        ),
    ]
