# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-09 18:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200209_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerconcussionwaiver',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerconcussionwaiver',
            name='submitted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_concussion_waiver_submitted_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
