# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-06 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20211011_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='guardian_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
