# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-04 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0016_fieldnames_hidden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='code',
            field=models.CharField(blank=True, help_text='Leaving this field empty will generate a random code.', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='note',
            field=models.TextField(blank=True, help_text='What is the coupon for?'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='type',
            field=models.CharField(choices=[('full', 'Full Value'), ('percentage', 'Percentage'), ('amount', 'Amount')], max_length=20),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='use_count',
            field=models.IntegerField(default=0, help_text='How many times the coupon has been used'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='use_limit',
            field=models.IntegerField(default=1, help_text='How many uses the coupon should have'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Leave empty for coupons that never expire', null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='type',
            field=models.CharField(choices=[('indoor', 'Indoor'), ('outdoor', 'Outdoor')], max_length=32),
        ),
        migrations.AlterField(
            model_name='fieldnames',
            name='type',
            field=models.CharField(choices=[('grass', 'Grass'), ('turf', 'Turf')], max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='baggage',
            field=models.IntegerField(help_text='max group size'),
        ),
        migrations.AlterField(
            model_name='league',
            name='captaining_note',
            field=models.TextField(blank=True, help_text='note for captaining, typically captain meeting date and time'),
        ),
        migrations.AlterField(
            model_name='league',
            name='check_cost_increase',
            field=models.IntegerField(help_text='amount to be added to paypal_cost if paying by check'),
        ),
        migrations.AlterField(
            model_name='league',
            name='detailed_info',
            field=models.TextField(help_text='details page text, use HTML'),
        ),
        migrations.AlterField(
            model_name='league',
            name='division_captains_email',
            field=models.CharField(blank=True, help_text='email address for league captains', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='division_email',
            field=models.CharField(blank=True, help_text='email address for just this league', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='end_time',
            field=models.TimeField(help_text='end time for league', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='fields',
            field=models.ManyToManyField(help_text='Select the fields these games will be played at, use the green "+" icon if we\'re playing at a new field.', through='leagues.LeagueFields', to='leagues.Field'),
        ),
        migrations.AlterField(
            model_name='league',
            name='gender',
            field=models.CharField(choices=[('capandfill', 'Cap-and-Fill'), ('corec', 'Co-Rec'), ('mens', "Men's"), ('mixed', 'Mixed'), ('open', 'Open'), ('womens', "Women's")], max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='group_lock_start_date',
            field=models.DateTimeField(help_text='date and time that groups are locked'),
        ),
        migrations.AlterField(
            model_name='league',
            name='late_cost_increase',
            field=models.IntegerField(help_text='amount to be added to paypal_cost if paying after price_increase_start_date'),
        ),
        migrations.AlterField(
            model_name='league',
            name='league_end_date',
            field=models.DateField(help_text='date of last game'),
        ),
        migrations.AlterField(
            model_name='league',
            name='league_start_date',
            field=models.DateField(help_text='date of first game'),
        ),
        migrations.AlterField(
            model_name='league',
            name='level',
            field=models.CharField(choices=[('comp', 'Competitive'), ('rec', 'Recreational'), ('youth', 'Youth')], max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='mail_check_address',
            field=models.TextField(help_text='treasurer mailing address'),
        ),
        migrations.AlterField(
            model_name='league',
            name='max_players',
            field=models.IntegerField(help_text='max players for league, extra registrations will be placed on waitlist'),
        ),
        migrations.AlterField(
            model_name='league',
            name='min_age',
            field=models.IntegerField(default=0, help_text='minimum age (in years)'),
        ),
        migrations.AlterField(
            model_name='league',
            name='night',
            field=models.CharField(help_text='lower case, no special characters, e.g. "sunday", "tuesday and thursday", "end of season tournament"', max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='num_games_per_week',
            field=models.IntegerField(default=1, help_text='number of games per week, used to calculate number of games for a league'),
        ),
        migrations.AlterField(
            model_name='league',
            name='num_skip_weeks',
            field=models.IntegerField(default=0, help_text='number of weeks skipped, e.g. skipping 4th of July'),
        ),
        migrations.AlterField(
            model_name='league',
            name='num_time_slots',
            field=models.IntegerField(default=1, help_text='number of time slots'),
        ),
        migrations.AlterField(
            model_name='league',
            name='paypal_cost',
            field=models.IntegerField(help_text='base cost of league if paying by PayPal'),
        ),
        migrations.AlterField(
            model_name='league',
            name='price_increase_start_date',
            field=models.DateTimeField(help_text='date and time when cost increases for league'),
        ),
        migrations.AlterField(
            model_name='league',
            name='reg_start_date',
            field=models.DateTimeField(help_text='date and time that registration process is open (not currently automated)'),
        ),
        migrations.AlterField(
            model_name='league',
            name='registration_prompt',
            field=models.TextField(blank=True, help_text='prompt to show during registration, e.g. to collect data around format preference'),
        ),
        migrations.AlterField(
            model_name='league',
            name='schedule_note',
            field=models.TextField(blank=True, help_text='note to appear under the schedule'),
        ),
        migrations.AlterField(
            model_name='league',
            name='start_time',
            field=models.TimeField(help_text='start time for league', null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='state',
            field=models.CharField(choices=[('cancelled', 'Cancelled - visible to all, registration closed to all'), ('closed', 'Closed - visible to all, registration closed to all'), ('hidden', 'Hidden - hidden to all, registration closed to all'), ('open', 'Open - visible to all, registration conditionally open to all'), ('preview', 'Preview - visible only to admins, registration conditionally open only to admins')], help_text='state of league, changes whether registration is open or league is visible', max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='summary_info',
            field=models.TextField(help_text='notes for league, e.g. 50-50 league format, showcase league notes'),
        ),
        migrations.AlterField(
            model_name='league',
            name='tagline',
            field=models.TextField(blank=True, help_text='short tagline for description fields, e.g. SEO, Facebook, etc.'),
        ),
        migrations.AlterField(
            model_name='league',
            name='times',
            field=models.TextField(help_text='start to end time, e.g. 6:00-8:00pm'),
        ),
        migrations.AlterField(
            model_name='league',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('league', 'League'), ('tournament', 'Tournament')], max_length=32),
        ),
        migrations.AlterField(
            model_name='league',
            name='waitlist_start_date',
            field=models.DateTimeField(help_text='date and time that waitlist is started (regardless of number of registrations)'),
        ),
        migrations.AlterField(
            model_name='league',
            name='year',
            field=models.IntegerField(help_text='four digit year, e.g. 2013'),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('check', 'Check'), ('paypal', 'PayPal')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='registrations',
            name='prompt_response',
            field=models.CharField(blank=True, help_text='response to the registration prompt for a division', max_length=255, null=True),
        ),
    ]
