# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-06 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20200204_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='published',
            field=models.DateTimeField(help_text='Posts with a published date in the future will be hidden until that date'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('plain', 'Plain')], help_text='<a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Get Help with Markdown</a> | <a href="https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics" target="_blank">Get Help with HTML</a>', max_length=8),
        ),
        migrations.AlterField(
            model_name='staticcontent',
            name='type',
            field=models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('plain', 'Plain')], help_text='<a href="https://www.markdownguide.org/basic-syntax/" target="_blank">Get Help with Markdown</a> | <a href="https://developer.mozilla.org/en-US/docs/Learn/Getting_started_with_the_web/HTML_basics" target="_blank">Get Help with HTML</a>', max_length=32),
        ),
        migrations.AlterField(
            model_name='staticmenuitems',
            name='content',
            field=models.CharField(help_text='Text a user will see', max_length=64),
        ),
        migrations.AlterField(
            model_name='staticmenuitems',
            name='href',
            field=models.CharField(blank=True, help_text='Use with "External Link", "Internal Link", and "Static Link"', max_length=255),
        ),
        migrations.AlterField(
            model_name='staticmenuitems',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, help_text='Only "Header" type items can be parents', null=True, on_delete=django.db.models.deletion.CASCADE, to='index.StaticMenuItems'),
        ),
        migrations.AlterField(
            model_name='staticmenuitems',
            name='position',
            field=models.IntegerField(help_text='Order of sibling items within a parent'),
        ),
        migrations.AlterField(
            model_name='staticmenuitems',
            name='type',
            field=models.CharField(choices=[('header', 'Header'), ('external_link', 'External Link'), ('internal_link', 'Internal Link'), ('static_link', 'Static Link'), ('text', 'Text')], help_text='<ul><li>Header - text header for grouping content</li><li>External Link - link to an external page (set `href` field to a full web address starting with "https://")</li><li>Internal Link - link to a page on the website (set `href` field to a relative url starting with "/")</li><li>Static Link - link off to static content in the app (set `href` field to a relative url starting with "/")</li><li>Text - plain text</li></ul>', max_length=32),
        ),
    ]
